### ISSUE TITLE
Moved to GitLab

### ISSUE THREAD

**Issue by shaicoleman** [HoneyryderChuck/httpx#1]
This repo is out of date, the latest version is on:
https://gitlab.com/honeyryderchuck/httpx

Perhaps it's best to archive this repo to avoid confusion

**Comment by HoneyryderChuck** [comment]
Hi,

This github repo is supposed to be a mirror of the upstream from gitlab you just linked. However, mirroring has been broken since [github deprecated its API usage when using basic auth, first for 2FA-enabled accounts, then for everyone recently](https://developer.github.com/changes/2020-02-14-deprecating-password-auth/).

The other issue is that gitlab's mirroring feature only supports basic auth for https-based mirrors, so until gitlab supports using access tokens for mirroring, this mirror will remain outdated.

For documentation, [I've created a feature request in the gitlab project](https://gitlab.com/gitlab-org/gitlab/-/issues/262870), if you want to follow up on that.

I'll leave your issue open, for anyone who might be interested on the why.

**Comment by karlwilbur** [comment]
@HoneyryderChuck I have a server that I am using to back up all of my Git repos outside of GitHub. If you want to, you can add my machine account ([`kandr-admins`](https://github.com/kandr-admins)) to this repo, then I can have Jenkins pull from GitLab (I can to this already with public access) and push here using my existing SSH auth. I'll just add it to my nightly script, or create something custom with a shorter interval. This could be a possible workaround until something more desirable is supported across GitHub and GitLab.

**Comment by HoneyryderChuck** [comment]
@karlwilbur thank you, but I'd rather own this process.

**Comment by noraj** [comment]
Please add a link to https://gitlab.com/honeyryderchuck/httpx here 
![image](https://user-images.githubusercontent.com/16578570/122887116-e0558200-d340-11eb-882a-6f37fbdf17ab.png)
eg.
![image](https://user-images.githubusercontent.com/16578570/122887212-f6fbd900-d340-11eb-875b-ad713a4ea037.png)

**Comment by HoneyryderChuck** [comment]
@noraj done

**Comment by noraj** [comment]
I guess this issue can be closed now 😃

**Comment by karlwilbur** [comment]
Well, it doesn't resolve the original issue of this repo being out of date. I believe that setting up a sync system as I suggested will address that, at which point we could close the issue.

**Comment by HoneyryderChuck** [comment]
what @karlwilbur said. It's not out-of-date as of now though, as I did a manual update. Ticket remains open though.

**Comment by noraj** [comment]
The Gitlab -> Github mirror is not automatic? you push updates manually?

Here is how setup a [push mirror from GitLab to GitHub](https://docs.gitlab.com/ee/user/project/repository/repository_mirroring.html#setting-up-a-push-mirror-from-gitlab-to-github). I have done it for several repositories, it works well.

I even found a way to "sync" [issues and PRs](https://blog.raw.pm/en/gitlab-github-sync/).

**Comment by HoneyryderChuck** [comment]
That setup doesn't work for me, see https://github.com/HoneyryderChuck/httpx/issues/1#issuecomment-790939052

**Comment by noraj** [comment]
> That setup doesn't work for me, see [#1 (comment)](https://github.com/HoneyryderChuck/httpx/issues/1#issuecomment-790939052)

I read that but I still don't see the point, you don't need basic auth for push mirror since both repository are public, just use access token. In the password field you are no supposed to put your Github password but the private token you generated from [Personal access tokens](https://github.com/settings/tokens).

**Comment by HoneyryderChuck** [comment]
I see, I had never tried setting the token as the password.

However, that doesn't seem to be enough in my case:

<img width="272" alt="Captura de ecrã 2021-06-23, às 11 34 12" src="https://user-images.githubusercontent.com/215707/123064446-f2095900-d416-11eb-9ce5-3f982b4ff859.png">

**Comment by karlwilbur** [comment]
@HoneyryderChuck FWIW, I'm still willing to get you set up on my Jenkins mirroring schedule (described in my earlier comment), if only as an interim solution while you get something in place which better suits your needs. PGP-signing your commits, a good practice in any case, would ensure that no corruption or nefarious changes occur on my end.

I understand and don't disagree with the desire to own the process and I am not trying to change your mind on that; only saying that I am still willing to help.

**Comment by karlwilbur** [comment]
Another solution, if you have a server with some resources to spare, would be to set up a cron job somewhere and mirror to that server, then push that mirror to GitHub. I think that this is essentially what Jenkins is doing, only in Java instead of Bash+cron.

If you think that would work for you, I can write some scripts and push them up as a Gist.

**Comment by HoneyryderChuck** [comment]
@karlwilbur I didn't change my opinion, however, I'm deeply appreciative that the community is willing to put their resources available for this, thank you for that.

I actually thought about the cronjob possibility, but I'm settling in a git post-hook that'll push to a (or many) backup(s) on push to master. Still have to do it though. A bit brittle and single point of failure, but it's a reasonable workaround until all this gets automated.

**Comment by noraj** [comment]
I just made a PoC with the new token and it works like a charm.

Check full repo control for the access token:

![image](https://user-images.githubusercontent.com/16578570/123139434-7deea580-d456-11eb-841b-e66a5cd13a02.png)

On the Gitlab end don't forget to put your username and use the `.git` at he end in the URL then access token as password.

![image](https://user-images.githubusercontent.com/16578570/123139707-c908b880-d456-11eb-96f0-245ee0aade4b.png)

The feature work and is not broken, you must have made a mistake most probably in the URL.

**Comment by HoneyryderChuck** [comment]
I tried it again, and seems to have worked!

AFAIK there was nothing wrong with the URLs, however I set full repo permissions on the token, instead of just `public_repo`, like the gitlab documentation states. Maybe that's what caused it, @noraj ?

Seems I can finally close this issue then :) Thx everyone.

**Comment by noraj** [comment]
In theory [public_repo](https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps) should be enough:

> Limits access to public repositories. That includes read/write access to code, commit statuses, repository projects, collaborators, and deployment statuses for public repositories and organizations. Also required for starring public repositories.

I set full perm for my PoC to be sure and my production syncs are using old token format before permissions where such fine grained. You could test with `public_repo` only this should work in theory.
