### ISSUE TITLE
Proxy Error Retry Handling and General Thoughts

### ISSUE THREAD

**Issue by Aubermean** [HoneyryderChuck/httpx#26]
Hi Tiago, to begin I want to offer my deepest gratitude for your continued work to support Ruby with a modernized, updated HTTP library. I read your recent article, and it convinced me - I have been refactoring a lot, moving from Typheous and all other HTTP libs.

HTTPX has been a breeze for many simple things. The issues and quirks I am struggling with most is concurrent connections to the same host which go out on multiple proxies. In hindsight, re-reading your article, I think you didn't give Hydra/ethon quite enough credit/mention. Especially for the aforementioned use case which I don't imagine is all that uncommon: proxies on a per request basis, requests added to a queue and then run concurrently, all connecting to the same host.

Still, I am determined to stick with HTTPX and dump the rest. But wanted to bring to your attention the last few feature gaps I am experiencing between Typheous and HTTPX.

Connecting to SOCKS5 only (not HTTP proxies...) I receive these errors quite frequently:

```
socks5 negotiation error: 1 (HTTPX::Socks5Error)
Failed to connect to proxy (HTTPX::HTTPProxyError)
```

The only other errors I have seen are `HTTPX::ReadTimeoutError`, `HTTPX::ConnectionError`, and of course the intermittently predictable good old `HTTPX::ErrorResponse`.

At the moment, I use the retries plugin like this:

```

    ERROR_CLASSES = [
      RuntimeError,
      HTTPX::HTTPProxyError,
      HTTPX::Socks5Error,
      HTTPX::ReadTimeoutError,
      HTTPX::ConnectionError,
      HTTPX::ErrorResponse
    ].freeze
    
     HTTPX
        .plugin(:follow_redirects)
        .plugin(:proxy).with_proxy(uri: proxy_uri)
        .plugin(:retries, max_retries: 10, retry_change_requests: true,
         retry_on: ->(res) { ERROR_CLASSES.any? { |error_class| res.error.is_a?(error_class) } })

```

I don't know if this is the best way to handle things. But still, it seems that HTTPX::Socks5Error and HTTPX::HTTPProxyError specifically are not being retried. Refactoring above to use constants while writing this (before using an array in a method)... I'm now getting `NameError: uninitialized constant HTTPX::HTTPProxyError`. So I will now explicitly `require 'httpx/plugins/proxy/http'` and `require 'httpx/plugins/proxy/socks5'` but am concerned this might have other knock on effects...

Looking at your code, if I were able to contribute to your work to improve things I would, but honestly it is quite out of my depth at the moment!

Other notes:

1. The gem is incredibly hard to find due to httpx being a python library, and surfacing first and muddying searches. A while back when I saw it 'ticked all the boxes' for Faraday, I literally couldn't find httpx. I really like the name, but perhaps using 'httpx.rb' or similar will help the library gain more visibility and traction.

2. Your 'wiki' is absolutely excellent, but finding and navigating it is a nightmare. On an Ultrawide monitor, the narrow width, short page length, and constant back and forths make it cumbersome. I think you should consider putting it all on a single page, so one can Ctrl+F and easily jump around. It should be front and center.

3. Navigating from your homepage to the Readme, not to nitpick or sound dramatic... but I have a superwide, ugly fonted un-navigable rdoc iframe, that makes it feel as if I have fallen into a ASP.NET blackhole. Maybe link directly to the Documentation/Rdocs instead, which is basically the same readme with navigation. Consider also tweaking the Rdocs theme to be as modern as the library itself is.

4. Finally, the domain itself - honeyryderchuck - makes my tabs hard to recognize and harder to find the httpx docs/site in Safari navbar. It might be time to let httpx shine on its own!

These might seem like perfectionistic criticisms, but image and packaging is everything. A little bit of work around the library could do wonders for the library itself.

Again, as Ruby lover and supporter, deepest thanks for all your work.

**Comment by HoneyryderChuck** [comment]
Hey, thx for the feedback and giving it a try!

> in hindsight, re-reading your article, I think you didn't give Hydra/ethon quite enough credit/mention. Especially for the aforementioned use case...

Can I ask you to be more specific in this part, and provide examples using hydra which you think aren't covered well in httpx? It may be a legitimate missing feature, or just an existing and less documented one, but I'd need to access it first.

> Connecting to SOCKS5 only (not HTTP proxies...) I receive these errors quite frequently...

I think this is definitely a bug (retries plugin not handling proxy errors by default). I think it can be quickly fixed, I'll work on a patch. Your workaround using `retry_on` is definitely a good one though.

About the rest:

1. I know what you mean, I also find it confusing it. Hindsight doesn't help much, as this library was registered some 6 months before the python counterpart. That python as a community is much bigger and commands more search results as a result doesn't help. But I don't think that suffixing ".rb" will help much tbh, I also get confused with "http or httprb", and this would make it worse. Renaming is not an option at this stage anyway. I can just hope ruby gets bigger again.
2. You had me with "excellent" and "nightmare" at the same time 😂 I don't think I'll be able to find time to work on wiki layouts soon, and this seems to optimize for a particular workstation set. However, I'll think about perhaps exposing the wiki directly in the repo, so these contributions can be made by the community (the wiki is a separate hidden git repo which does not accept pull requests, that's a missing feature in both gitlab and github).
3. The RDoc pages are build using [hanna-nouveau](https://github.com/jeremyevans/hanna), and this discrepancy can also be observed in [the sequel doc page](https://sequel.jeremyevans.net/documentation.html) (press README and tell me whether the issue is the same). I can't do too much about the layouts without investing significant time in it, time which is already limited to maintain the lib, and that's why I'm mostly applying some widely available theme both for docs as well as homepage, which is free and easy to set up, but does not stand out as a result. Perhaps this is again just a matter of enabling a community member to improve it, so if you're up to the task, just [start from here](https://gitlab.com/os85/httpx/-/blob/master/Rakefile?ref_type=heads#L51-58). Btw what do you mean with "Maybe link directly to the Documentation/Rdocs instead"?
4. I think that would require acquiring a domain, or creating an http orga on gitlab or github. That would unfortunately only increase the maintenance overhead at this point. And this still being mostly maintained by 1 person, I'm not yet at the point where this will make a significant impact. Maybe when it gets 10million downloads 😂 I'm also not sure how you organize tabs, as I mostly rely on the page title.

I appreciate the feedback though, and I'll see about making some improvements where possible, while enabling you to help.

**Comment by Aubermean** [comment]
Thank you Tiago. Will circle back to this. Flooded at the moment. Small note is that I have noted a slowdown moving from httpx 1.1.5 to master branch. Haven't been able to figure out why yet!
