### ISSUE TITLE
HTTPX stuck utilizing 100% CPU

### ISSUE THREAD

**Issue by j-manu** [HoneyryderChuck/httpx#59]
I have an app which gets stuck using 100% CPU on an HTTPX call. I obtained a stacktrace  using SIGQUIT.

```
/home/app/hub-self/shared/bundle/ruby/3.1.0/gems/httpx-1.3.0/lib/httpx/pool.rb:273:in `compact'
/home/app/hub-self/shared/bundle/ruby/3.1.0/gems/httpx-1.3.0/lib/httpx/pool.rb:273:in `next_timeout'
/home/app/hub-self/shared/bundle/ruby/3.1.0/gems/httpx-1.3.0/lib/httpx/pool.rb:39:in `block in next_tick'
/home/app/hub-self/shared/bundle/ruby/3.1.0/gems/httpx-1.3.0/lib/httpx/pool.rb:38:in `catch'
/home/app/hub-self/shared/bundle/ruby/3.1.0/gems/httpx-1.3.0/lib/httpx/pool.rb:38:in `next_tick'
/home/app/hub-self/shared/bundle/ruby/3.1.0/gems/httpx-1.3.0/lib/httpx/pool.rb:66:in `close'
/home/app/hub-self/shared/bundle/ruby/3.1.0/gems/httpx-1.3.0/lib/httpx/session.rb:45:in `close'
/home/app/hub-self/shared/bundle/ruby/3.1.0/gems/httpx-1.3.0/lib/httpx/session.rb:286:in `receive_requests'
/home/app/hub-self/shared/bundle/ruby/3.1.0/gems/httpx-1.3.0/lib/httpx/session.rb:237:in `send_requests'
/home/app/hub-self/shared/bundle/ruby/3.1.0/gems/httpx-1.3.0/lib/httpx/session.rb:72:in `request'
/home/app/hub-self/shared/bundle/ruby/3.1.0/gems/httpx-1.3.0/lib/httpx/chainable.rb:10:in `get'
```

The code in question is standard - `HTTPX.with(timeout: {operation_timeout: 120}).get(api_url, params: params)`

**Comment by HoneyryderChuck** [comment]
Hi @j-manu ,

Can you reproduceit detrministically locally? If so, can you run it with HTTPX_DEBUG=3 and post the output here?

**Comment by diogovernier** [comment]
Hey there! First off, thanks for this awesome, gem!

Unfortunately, this happens to me as well, with concurrent requests, when I fetch random URLs from a list in a rails console:

```rb
Benchmark.realtime do
  HTTPX.with(timeout: { operation_timeout: 30 }).get(*url_list.sample(100))
end
```

I ran with `HTTPX_DEBUG=3` and it stops logging right before getting stuck. This is the latest part of the debug info: ( I am attaching more, basically everything I had in my console buffer)
[httpx_logs.txt](https://github.com/user-attachments/files/16495355/httpx_logs.txt)
:

```
1: frame was received!
1: {:length=>0, :type=>:data, :flags=>[:end_stream], :stream=>1, :payload=>0}
1: <- DATA: 0 bytes...
1: <- ""
1: closing stream
[ELAPSED TIME]: Session -> response: 24167 (ms)
[ELAPSED TIME]: Session -> response: 24167 (ms)
[ELAPSED TIME]: Session -> response: 24167 (ms)
```

Also, I ran this command in the hanging thread:

```
rbtrace -p 28112 -e 'Thread.new{ require "stackprof"; StackProf.start(mo
de: :cpu); sleep 2; StackProf.stop; StackProf.results("/tmp/perf"); }'
```

Then, when I run `stackprof /tmp/perf`, I get:

```
==================================
  Mode: cpu(1000)
  Samples: 209 (0.00% miss rate)
  GC: 20 (9.57%)
==================================
     TOTAL    (pct)     SAMPLES    (pct)     FRAME
        44  (21.1%)          28  (13.4%)     HTTPX::Connection::HTTP2#interests
        90  (43.1%)          28  (13.4%)     HTTPX::Connection#interests
        39  (18.7%)          27  (12.9%)     Enumerable.filter_map
        22  (10.5%)          21  (10.0%)     HTTPX::Buffer#empty?
        18   (8.6%)          18   (8.6%)     (sweeping)
       127  (60.8%)          13   (6.2%)     HTTPX::Selector#select_many
       125  (59.8%)          13   (6.2%)     Array#delete_if
         9   (4.3%)           9   (4.3%)     Array#include?
         8   (3.8%)           8   (3.8%)     HTTPX::Connection#connecting?
         5   (2.4%)           5   (2.4%)     HTTPX::Connection#timeout
        37  (17.7%)           4   (1.9%)     Array#each
        48  (23.0%)           4   (1.9%)     HTTPX::Pool#next_timeout
         4   (1.9%)           3   (1.4%)     HTTPX::Buffer#full?
         3   (1.4%)           3   (1.4%)     HTTPX::Timers#fire
         4   (1.9%)           2   (1.0%)     Array#reject
         2   (1.0%)           2   (1.0%)     HTTPX::Resolver::Native#interests
         5   (2.4%)           2   (1.0%)     HTTPX::Plugins::InternalTelemetry::InstanceMethods#fetch_response
         3   (1.4%)           2   (1.0%)     Hash#delete
         2   (1.0%)           2   (1.0%)     (marking)
       189  (90.4%)           2   (1.0%)     HTTPX::Session#receive_requests
       189  (90.4%)           2   (1.0%)     Kernel.catch
         1   (0.5%)           1   (0.5%)     Array#map
         1   (0.5%)           1   (0.5%)     Array#all?
         1   (0.5%)           1   (0.5%)     String#empty?
         1   (0.5%)           1   (0.5%)     HTTPX::Utils.now
         3   (1.4%)           1   (0.5%)     HTTPX::Resolver::Native#timeout
         1   (0.5%)           1   (0.5%)     Kernel.hash
         1   (0.5%)           1   (0.5%)     String#bytesize
         1   (0.5%)           1   (0.5%)     Thread#[]
         2   (1.0%)           1   (0.5%)     HTTPX::Resolver::Multi#closed?
```

I hope that helps to debug.

**Comment by diogovernier** [comment]
Similarly, from another thread:

```
==================================
  Mode: cpu(1000)
  Samples: 209 (0.00% miss rate)
  GC: 17 (8.13%)
==================================
     TOTAL    (pct)     SAMPLES    (pct)     FRAME
        80  (38.3%)          42  (20.1%)     Enumerable.filter_map
        37  (17.7%)          26  (12.4%)     HTTPX::Connection::HTTP2#interests
        21  (10.0%)          21  (10.0%)     HTTPX::Connection#timeout
        67  (32.1%)          16   (7.7%)     HTTPX::Connection#interests
        15   (7.2%)          15   (7.2%)     (sweeping)
        15   (7.2%)          15   (7.2%)     HTTPX::Buffer#empty?
        78  (37.3%)          13   (6.2%)     Array#each
        94  (45.0%)           9   (4.3%)     HTTPX::Selector#select_many
        89  (42.6%)           7   (3.3%)     Array#delete_if
         7   (3.3%)           7   (3.3%)     Array#include?
         5   (2.4%)           5   (2.4%)     HTTPX::Connection#connecting?
         5   (2.4%)           5   (2.4%)     HTTPX::Buffer#full?
       192  (91.9%)           4   (1.9%)     HTTPX::Session#receive_requests
         4   (1.9%)           3   (1.4%)     HTTPX::Resolver::Native#timeout
        89  (42.6%)           3   (1.4%)     HTTPX::Pool#next_timeout
         2   (1.0%)           2   (1.0%)     Array#min
         2   (1.0%)           2   (1.0%)     Kernel.block_given?
         2   (1.0%)           2   (1.0%)     (marking)
         2   (1.0%)           2   (1.0%)     Array#compact
       192  (91.9%)           2   (1.0%)     Kernel.catch
         1   (0.5%)           1   (0.5%)     HTTPX::Resolver::Native#interests
         1   (0.5%)           1   (0.5%)     Hash#values
         1   (0.5%)           1   (0.5%)     HTTPX::Utils.now
         1   (0.5%)           1   (0.5%)     Thread.current
         1   (0.5%)           1   (0.5%)     Array#all?
         1   (0.5%)           1   (0.5%)     Kernel.hash
       192  (91.9%)           1   (0.5%)     Kernel.loop
       186  (89.0%)           1   (0.5%)     HTTPX::Pool#next_tick
       192  (91.9%)           0   (0.0%)     MissionControl::Jobs::Adapter#activating
       192  (91.9%)           0   (0.0%)     MissionControl::Jobs::Console::Context#evaluate
```

**Comment by j-manu** [comment]
> Hi @j-manu ,
> 
> Can you reproduceit detrministically locally? If so, can you run it with HTTPX_DEBUG=3 and post the output here?

Sorry. The URL it was having issues with is an internal service and has side effects. So I can't reproduce it. While the problem was ongoing, I also ran strace on the stuck process and the output was the following repeated endlessly

```
ppoll([{fd=8, events=POLLIN}], 1, NULL, NULL, 8) = 1 ([{fd=8, revents=POLLIN}])
getpid()
```

The URL which caused the error, could take up to 120 seconds to respond. That was the only distinguishing factor.

**Comment by HoneyryderChuck** [comment]
@diogovernier thx for the logs, I'll analyse in more detail during the week. From an earlier look, it seems that your issue is around tls connection handshake, or am I mistaken? Do you see such issues using other http clients? 

@j-manu logs from an earlier version won't help. I can see that there's a busy loop around an existing connection, but I don't know its stated nor whether it dealt with all requests in it, hence why I need more detailed debugging.

**Comment by diogovernier** [comment]
thx @HoneyryderChuck !

>  it seems that your issue is around tls connection handshake, or am I mistaken?
Hum, no. Maybe you saw some errors in the logs I sent due to a broken test URL that was sampled in the benchmark? But the issue I am experiencing is the 100% cpu usage as well. SSL, etc. seems to be working fine.

> Do you see such issues using other http clients?
I didn't test parallel requests with other HTTP clients yet. But single requests are working in any client.

**Comment by diogovernier** [comment]
hey @HoneyryderChuck , I can consistently reproduce this locally, with this code:

```rb
  list = ["https://rubyreferences.github.io/rubychanges/feed.xml", "https://upcoder.com/feed", "https://slack.design/feed/", "https://newsletter.ruder.io/feed", "https://blog.codelitt.com/rss/", "https://medium.com/feed/engineering-housing", "http://neopythonic.blogspot.com/feeds/posts/default", "https://jalammar.github.io/feed.xml", "https://dave.cheney.net/feed", "https://railsatscale.com/feed.xml"]
  
  HTTPX.with(timeout: { operation_timeout: 5 }).get(*list)
```

I did some debugging, and I think that happens because of the connection coalescing at this point: 
https://github.com/HoneyryderChuck/httpx/blob/72786476888c73a2f94df3333d43b828d3c1c076/lib/httpx/pool.rb#L217-L223

For instance, the first URL is `https://rubyreferences.github.io/rubychanges/feed.xml` and the 8th URL is `https://jalammar.github.io/feed.xml`, by the time the 8th is resolved, the connection to the first one has a high change of being already open (because of the many URLs in between them), therefore line `219` is executed, and `throw(:coalesced, found_connection)` is executed. If I am not mistaken, this is changing the control flow, and for some reason `HTTPX::Resolver::Native#resolve` is no longer called, which makes it so the remaining 2 URLs are not resolved. Also, for some other reason I don't understand, looks like this makes it so the following line in `HTTPX::Session` stays in an infinite loop, apparently because it is trying to fetch a response for a request whose domain is never going to be resolved:

```rb
  catch(:coalesced) { pool.next_tick } until (response = fetch_response(request, connections, request.options))
```

I might be wrong. But I hope this at least gives you some pointer for debugging.

Again, I really enjoying this gem. Thanks for all the great work on this. I would be glad to hop a call if you are having trouble reproducint and want to pair on debugging this (I guess we could even speak portuguese, am I right? lol)

**Comment by diogovernier** [comment]
If I comment this line, the execution completes, and I can no longer reproduce the issue:

```
 throw(:coalesced, found_connection) unless @connections.include?(connection)
```
Of course, this might break something downstream. But just so you have an idea.

**Comment by diogovernier** [comment]
I have limited time now, but I started my fix attempt: https://github.com/HoneyryderChuck/httpx/pull/60. I will improve the PR description, etc. but if you could take a look that would be awesome.

**Comment by HoneyryderChuck** [comment]
Hi @diogovernier 👋 thx for the investigation and the potential fix!

I see, so the issue is with connection coalescing on multiple requests. That makes sense, considering the test suite does not run on an Happy Eyeballs enabled environment (gitlab docker executors are IPv4 only), so something definitely went through the cracks.

I'm currently in the process of revamping the connection pooling strategy. This issue is not the only motivator, but I expect it to have eliminated this issue, considering that it won't rely on throw/catch. Nevertheless, it may take some time for this to be ready (my time has been limited recently), so I'm not against a small fix like yours if it deals with the majority of the issues reported here. I'd kindly ask everyone else involved in this thread to try it out therefore.

That fix would have to be applied to other resolvers, btw (the DoH resolver also catches `:coalesced`). In the end, it may be wiser to move that `catch` inside `emit_addresses`.

I'll have a further look at this next week, when I'll be able to test your repro script. Thx again sofar!

**Comment by diogovernier** [comment]
Nice! I am excited for this revamp work to come out then. Thanks so much!
